services:
  # Database container init
  db:
    image: postgres:17.5
    container_name: postgres_db
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '${DB_PORT}:${DB_PORT}'

  # Backend container init

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - '${BACKEND_PORT}:${BACKEND_PORT}'
    env_file:
      - ./.env

    # Frontend container init

  frontend:
    build:
      context: ./frontend/notes-webapp
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - '${FRONTEND_PORT}:${FRONTEND_PORT}'

# Volumes
volumes:
  postgres_data:
